/* ZOID Storefront — Complete Nigerian Universities, States & Cities Dataset */

export const NIGERIAN_STATES = [
  "Abia State",
  "Adamawa State",
  "Akwa Ibom State",
  "Anambra State",
  "Bauchi State",
  "Bayelsa State",
  "Benue State",
  "Borno State",
  "Cross River State",
  "Delta State",
  "Ebonyi State",
  "Edo State",
  "Ekiti State",
  "Enugu State",
  "FCT - Abuja",
  "Gombe State",
  "Imo State",
  "Jigawa State",
  "Kaduna State",
  "Kano State",
  "Katsina State",
  "Kebbi State",
  "Kogi State",
  "Kwara State",
  "Lagos State",
  "Nasarawa State",
  "Niger State",
  "Ogun State",
  "Ondo State",
  "Osun State",
  "Oyo State",
  "Plateau State",
  "Rivers State",
  "Sokoto State",
  "Taraba State",
  "Yobe State",
  "Zamfara State",
] as const;

export const NIGERIAN_UNIVERSITIES = [
  // Federal Universities
  "Abubakar Tafawa Balewa University, Bauchi (ATBU)",
  "Ahmadu Bello University, Zaria (ABU)",
  "Air Force Institute of Technology, Kaduna (AFIT)",
  "Alex Ekwueme Federal University, Ndufu-Alike (AE-FUNAI)",
  "Bayero University, Kano (BUK)",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Federal University of Petroleum Resources, Effurun (FUPRE)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University, Birnin Kebbi (FUBK)",
  "Federal University, Dutse (FUD)",
  "Federal University, Dutsin-Ma (FUDMA)",
  "Federal University, Gashua (FUGA)",
  "Federal University, Gusau (FUGUS)",
  "Federal University, Kashere (FUK)",
  "Federal University, Lafia (FULAFIA)",
  "Federal University, Lokoja (FULOKOJA)",
  "Federal University, Otuoke (FUOTUOKE)",
  "Federal University, Oye-Ekiti (FUOYE)",
  "Federal University, Wukari (FUWUKARI)",
  "Joseph Sarwuan Tarka University, Makurdi (formerly FUAM)",
  "Michael Okpara University of Agriculture, Umudike (MOUAU)",
  "Modibbo Adama University, Yola (MAU)",
  "National Open University of Nigeria (NOUN)",
  "Nigeria Police Academy, Wudil (POLAC)",
  "Nigerian Army University, Biu (NAUB)",
  "Nigerian Defence Academy, Kaduna (NDA)",
  "Nigerian Maritime University, Okerenkoko",
  "Nnamdi Azikiwe University, Awka (UNIZIK)",
  "Obafemi Awolowo University, Ile-Ife (OAU)",
  "University of Abuja, Gwagwalada (UNIABUJA)",
  "University of Benin, Benin City (UNIBEN)",
  "University of Calabar (UNICAL)",
  "University of Ibadan (UI)",
  "University of Ilorin (UNILORIN)",
  "University of Jos (UNIJOS)",
  "University of Lagos, Akoka (UNILAG)",
  "University of Maiduguri (UNIMAID)",
  "University of Nigeria, Nsukka (UNN)",
  "University of Port Harcourt (UNIPORT)",
  "University of Uyo (UNIUYO)",
  "Usmanu Danfodiyo University, Sokoto (UDUS)",

  // State Universities
  "Abia State University, Uturu (ABSU)",
  "Adamawa State University, Mubi (ADSU)",
  "Adekunle Ajasin University, Akungba-Akoko (AAUA)",
  "Akwa Ibom State University, Ikot Akpaden (AKSU)",
  "Ambrose Alli University, Ekpoma (AAU)",
  "Bauchi State University, Gadau (BASUG)",
  "Bayelsa Medical University, Yenagoa (BMU)",
  "Benue State University, Makurdi (BSUM)",
  "Borno State University, Maiduguri (BOSU)",
  "Chukwuemeka Odumegwu Ojukwu University, Uli (COOU)",
  "Confluence University of Science and Technology, Osara (CUSTECH)",
  "Delta State University of Science and Technology, Ozoro (DSUST)",
  "Delta State University, Abraka (DELSU)",
  "Dennis Osadebay University, Anwai-Asaba",
  "Ebonyi State University, Abakaliki (EBSU)",
  "Edo State University, Uzairue (EDSU)",
  "Ekiti State University, Ado-Ekiti (EKSU)",
  "Enugu State University of Science and Technology, Enugu (ESUT)",
  "Gombe State University, Gombe (GSU)",
  "Ibrahim Badamasi Babangida University, Lapai (IBBU)",
  "Ignatius Ajuru University of Education, Port Harcourt (IAUE)",
  "Imo State University, Owerri (IMSU)",
  "Kaduna State University, Kaduna (KASU)",
  "Kano University of Science and Technology, Wudil (KUST)",
  "Kebbi State University of Science and Technology, Aliero (KSUSTA)",
  "Kingsley Ozumba Mbadiwe University, Ogboko (KOMU)",
  "Kogi State University, Anyigba (Prince Abubakar Audu University)",
  "Kwara State University, Malete (KWASU)",
  "Lagos State University of Education, Ijanikin (LASUED)",
  "Lagos State University of Science and Technology, Ikorodu (LASUSTECH)",
  "Lagos State University, Ojo (LASU)",
  "Maitama Sule University, Kano (North-West University)",
  "Nasarawa State University, Keffi (NSUK)",
  "Niger Delta University, Wilberforce Island (NDU)",
  "Olabisi Onabanjo University, Ago-Iwoye (OOU)",
  "Olusegun Agagu University of Science and Technology, Okitipupa (OAUSTECH)",
  "Osun State University, Osogbo (UNIOSUN)",
  "Plateau State University, Bokkos (PLASU)",
  "Rivers State University, Port Harcourt (RSU)",
  "Sule Lamido University, Kafin Hausa (SLU)",
  "Tai Solarin University of Education, Ijagun (TASUED)",
  "Taraba State University, Jalingo (TSU)",
  "Umaru Musa Yar'adua University, Katsina (UMYU)",
  "University of Africa, Toru-Orua",
  "University of Cross River State, Calabar (UNICROSS)",
  "University of Delta, Agbor",
  "Yobe State University, Damaturu (YSU)",
  "Yusuf Maitama Sule University, Kano",
  "Zamfara State University, Talata Mafara",

  // Private Universities
  "Achievers University, Owo",
  "Adeleke University, Ede",
  "Admiralty University of Nigeria, Ibusa",
  "Afe Babalola University, Ado-Ekiti (ABUAD)",
  "African University of Science and Technology, Abuja (AUST)",
  "Ajayi Crowther University, Oyo",
  "Al-Hikmah University, Ilorin",
  "Al-Qalam University, Katsina",
  "Anchor University, Ayobo, Lagos",
  "Arthur Jarvis University, Akpabuyo",
  "Atiba University, Oyo",
  "Augustine University, Ilara, Epe",
  "Babcock University, Ilishan-Remo",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City (BIU)",
  "Bingham University, Karu",
  "Bowen University, Iwo",
  "Caleb University, Imota, Lagos",
  "Caritas University, Amorji-Nike, Enugu",
  "Chrisland University, Owode, Abeokuta",
  "Christopher University, Mowe",
  "Clifford University, Ihie",
  "Coal City University, Enugu",
  "Covenant University, Ota",
  "Crawford University, Igbesa",
  "Crescent University, Abeokuta",
  "Dominican University, Ibadan",
  "Edwin Clark University, Kiagbodo",
  "Eko University of Medicine and Health Sciences, Ijanikin",
  "Elizade University, Ilara-Mokin",
  "Evangel University, Akaeze",
  "Fountain University, Osogbo",
  "Godfrey Okoye University, Ugwuomu-Nike",
  "Greenfield University, Kaduna",
  "Gregory University, Uturu",
  "Hallmark University, Ijebu-Itele",
  "Hezekiah University, Umudi",
  "Igbinedion University, Okada",
  "Joseph Ayo Babalola University, Ikeji-Arakeji (JABU)",
  "Kings University, Odeomu",
  "KolaDaisi University, Ibadan",
  "Kwararafa University, Wukari",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Madonna University, Elele",
  "McPherson University, Seriki-Sotayo",
  "Mewar International University, Masaka",
  "Michael and Cecilia Ibru University, Agbarha-Otor",
  "Mountain Top University, Makogi Oba",
  "Nile University of Nigeria, Abuja",
  "Novena University, Ogume",
  "Obong University, Obong Ntak",
  "PAMO University of Medical Sciences, Port Harcourt",
  "Pan-Atlantic University, Ibeju-Lekki, Lagos (PAU)",
  "Paul University, Awka",
  "Philomath University, Kuje, Abuja",
  "Precious Cornerstone University, Ibadan",
  "Redeemer's University, Ede (RUN)",
  "Renaissance University, Ugbawka",
  "Rhema University, Aba",
  "Ritman University, Ikot Ekpene",
  "Salem University, Lokoja",
  "Skyline University Nigeria, Kano",
  "Southwestern University, Okun Owa",
  "Spiritan University, Nneochi",
  "Summit University, Offa",
  "Tansian University, Umunya",
  "Thomas Adewumi University, Oko-Irese",
  "Topfaith University, Mkpatak",
  "Trinity University, Yaba, Lagos",
  "Veritas University, Bwari, Abuja",
  "Wellspring University, Benin City",
  "Wesley University, Ondo",
  "Western Delta University, Oghara",
  "Wigwe University, Isiokpo",
];

export const NIGERIAN_CITIES_BY_STATE: Record<string, string[]> = {
  "Lagos State": [
    "Ikeja",
    "Victoria Island",
    "Lekki Phase 1",
    "Lekki Phase 2",
    "Ikoyi",
    "Yaba (Akoka / Sabo)",
    "Surulere",
    "Maryland",
    "Ajah",
    "Festac Town",
    "Gbagada",
    "Magodo Phase 1 & 2",
    "Alausa (CBD)",
    "Ogudu / Ojota",
    "Anthony Village",
    "Ilupeju",
    "Agege / Ogba",
    "Ikorodu",
    "Epe",
    "Badagry",
    "Apapa",
    "Lagos Island (Marina / CMS)",
    "Egbeda / Gowon Estate",
    "Ipaja / Ayobo",
    "Oshodi / Isolo",
    "Sangotedo",
    "Chevron / Conservation",
    "Ikate Elegushi",
    "Abraham Adesanya",
    "Oregun",
    "Bariga",
  ],
  "FCT - Abuja": [
    "Maitama",
    "Asokoro",
    "Wuse (Wuse 2 / Wuse Zone 1-7)",
    "Garki (Area 1-11)",
    "Gwarinpa Estate",
    "Jabi",
    "Utako",
    "Guzape",
    "Mabushi",
    "Katampe (Main & Extension)",
    "Life Camp",
    "Kubwa",
    "Lugbe (Airport Road)",
    "Lokogoma",
    "Apo (Resettlement / Legislative)",
    "Dutse Alhaji",
    "Bwari",
    "Kuje",
    "Karu / Nyanya",
    "Mpape",
    "Dawaki",
    "Jahi",
    "Kado",
    "Idu Industrial",
  ],
  "Rivers State": [
    "Port Harcourt (City)",
    "GRA Phase 1, 2 & 3",
    "Old GRA",
    "Peter Odili Road",
    "Trans Amadi Industrial",
    "D-Line",
    "Rumuola",
    "Rumuokwuta",
    "Rumuokoro",
    "Choba (Uniport Axis)",
    "Woji",
    "Elelenwo",
    "Borikiri",
    "Diobu (Mile 1-3)",
    "Oyigbo",
    "Eleme (Refinery / Indorama)",
    "Onne Free Zone",
    "Bonny Island",
    "Okrika",
    "Ahoada",
    "Ada-George",
    "Iwofe Road",
  ],
  "Oyo State": [
    "Ibadan (Bodija)",
    "Ibadan (Ring Road / Oluyole)",
    "Ibadan (Jericho / Eleyele)",
    "Ibadan (Dugbe / Mokola)",
    "Ibadan (Agodi GRA)",
    "Ibadan (Akobo / General Gas)",
    "Ibadan (Samonda / UI Axis)",
    "Ibadan (Challenge / Odo Ona)",
    "Ibadan (Iwo Road / Monatan)",
    "Ogbomoso",
    "Oyo Town",
    "Iseyin",
    "Saki",
    "Eruwa",
  ],
  "Ogun State": [
    "Abeokuta (Oke-Mosan / GRA)",
    "Abeokuta (Ibargun / Kuto)",
    "Sagamu",
    "Ijebu-Ode",
    "Ota (Covenant Axis)",
    "Mowe / Ofada",
    "Ibafo / Asese",
    "Magboro / Arepo",
    "Ogijo",
    "Ilaro",
    "Iperu-Remo",
    "Itele",
  ],
  "Anambra State": [
    "Awka (Capital / Ifite)",
    "Onitsha (Commercial / GRA)",
    "Nnewi (Industrial)",
    "Ekwulobia",
    "Ihiala",
    "Ogidi",
    "Obosi",
    "Nkpor",
    "Agulu",
  ],
  "Enugu State": [
    "Enugu (Independence Layout)",
    "Enugu (New Haven)",
    "Enugu (GRA)",
    "Enugu (Achara Layout / Coal Camp)",
    "Enugu (Ogui / Asata)",
    "Enugu (Abakpa Nike)",
    "Nsukka (UNN Axis)",
    "Udi",
    "Oji River",
    "Agbani",
  ],
  "Edo State": [
    "Benin City (GRA)",
    "Benin City (Ugbowo / UNIBEN Axis)",
    "Benin City (Airport Road / Boundary)",
    "Benin City (Ikpoba Hill / Aduwawa)",
    "Benin City (Ekenwan Road)",
    "Ekpoma (AAU Axis)",
    "Auchi",
    "Uromi",
    "Okada",
  ],
  "Delta State": [
    "Asaba (GRA / Nnebisi Road)",
    "Warri (GRA / Effurun)",
    "Sapele",
    "Ughelli",
    "Agbor",
    "Abraka (DELSU Axis)",
    "Oleh",
    "Ozoro",
    "Koko",
  ],
  "Kwara State": [
    "Ilorin (GRA / Fate Road)",
    "Ilorin (Tanke / Unilorin Axis)",
    "Ilorin (Taiwo / Challenge)",
    "Offa",
    "Omu-Aran",
    "Malete (KWASU Axis)",
    "Jebba",
  ],
  "Akwa Ibom State": [
    "Uyo (Ewet Housing / Shelter Afrique)",
    "Uyo (Itam / Ikot Ekpene Road)",
    "Eket",
    "Ikot Ekpene",
    "Oron",
    "Ikot Abasi",
  ],
  "Kaduna State": [
    "Kaduna (Barnawa / GRA)",
    "Kaduna (Malali / Millennium City)",
    "Kaduna (Kawo / Badarawa)",
    "Zaria (Samaru / ABU Axis)",
    "Kafanchan",
  ],
  "Kano State": [
    "Kano (Nassarawa GRA)",
    "Kano (Bompai / Sabon Gari)",
    "Kano (Fagge / Dala)",
    "Kano (Bayero University Axis)",
    "Wudil",
  ],
  "Abia State": [
    "Umuahia (GRA / Isi Gate)",
    "Aba (Faulks Road / Ariaria)",
    "Aba (GRA)",
    "Uturu (ABSU Axis)",
    "Ohafia",
  ],
  "Adamawa State": [
    "Yola (Jimeta / GRA)",
    "Mubi",
    "Numan",
    "Ganye",
  ],
  "Bauchi State": [
    "Bauchi (GRA / Yelwa)",
    "Azare",
    "Misau",
    "Gadau",
  ],
  "Bayelsa State": [
    "Yenagoa (Amarata / Kpansia)",
    "Yenagoa (Opolo / Etegwe)",
    "Otuoke (FUO Axis)",
    "Brass",
    "Sagbama",
  ],
  "Benue State": [
    "Makurdi (High Level / Wurukum)",
    "Makurdi (North Bank / FUAM Axis)",
    "Gboko",
    "Otukpo",
    "Katsina-Ala",
  ],
  "Borno State": [
    "Maiduguri (GRA / Bulumkutu)",
    "Biu",
    "Bama",
  ],
  "Cross River State": [
    "Calabar (State Housing / Marian)",
    "Calabar (Federal Housing / Etta Agbor)",
    "Ikom",
    "Ogoja",
    "Obudu",
  ],
  "Ebonyi State": [
    "Abakaliki (Mile 50 / Azuiyiokwu)",
    "Afikpo",
    "Onueke",
  ],
  "Ekiti State": [
    "Ado-Ekiti (GRA / Similoluwa)",
    "Ikere-Ekiti",
    "Oye-Ekiti",
    "Ijero-Ekiti",
  ],
  "Gombe State": [
    "Gombe (GRA / Pantami)",
    "Kaltungo",
    "Kashere",
  ],
  "Imo State": [
    "Owerri (Ikenegbu / Aladinma)",
    "Owerri (Works Layout / New Owerri)",
    "Orlu",
    "Okigwe",
    "Mbaise",
  ],
  "Jigawa State": [
    "Dutse (GRA)",
    "Hadejia",
    "Kazaure",
    "Gumel",
  ],
  "Katsina State": [
    "Katsina (GRA)",
    "Daura",
    "Funtua",
    "Dutsin-Ma",
  ],
  "Kebbi State": [
    "Birnin Kebbi (GRA)",
    "Argungu",
    "Yauri",
    "Zuru",
  ],
  "Kogi State": [
    "Lokoja (GRA / Ganaja)",
    "Anyigba (KSU Axis)",
    "Okene",
    "Kabba",
    "Idah",
  ],
  "Nasarawa State": [
    "Lafia (GRA)",
    "Keffi (NSUK Axis)",
    "Mararaba / Karu Border",
    "Akwanga",
  ],
  "Niger State": [
    "Minna (GRA / Tunga)",
    "Suleja",
    "Bida",
    "Kontagora",
  ],
  "Ondo State": [
    "Akure (Alagbaka / Ijapo GRA)",
    "Ondo Town",
    "Owo",
    "Ikare-Akoko",
    "Okitipupa",
  ],
  "Osun State": [
    "Osogbo (GRA / Ring Road)",
    "Ile-Ife (OAU / Mayfair Axis)",
    "Ede",
    "Ilesa",
    "Iwo",
  ],
  "Plateau State": [
    "Jos (Rayfield / GRA)",
    "Jos (Terminus / Anglo Jos)",
    "Bukuru",
    "Pankshin",
    "Bokkos",
  ],
  "Sokoto State": [
    "Sokoto (GRA / Runjin Sambo)",
    "Wamakko",
    "Tambuwal",
  ],
  "Taraba State": [
    "Jalingo (GRA)",
    "Wukari",
    "Bali",
    "Gembu",
  ],
  "Yobe State": [
    "Damaturu (GRA)",
    "Potiskum",
    "Gashua",
    "Nguru",
  ],
  "Zamfara State": [
    "Gusau (GRA)",
    "Talata Mafara",
    "Kaura Namoda",
  ],
};
