/* ZOID Concrete Ritual: checkout is the quiet handoff—focused, legible, and still rooted in the field archive. */
import { useState } from "react";
import { ArrowLeft, Check, LockKeyhole, Minus, Plus, Trash2 } from "lucide-react";
import { Link, useLocation } from "wouter";
import { formatNaira, useShop } from "@/contexts/ShopContext";

export default function Checkout() {
  const [, navigate] = useLocation();
  const { bag, count, total, removeFromBag } = useShop();
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", phone: "", address: "" });
  function update(field: keyof typeof form, value: string) { setForm((state) => ({ ...state, [field]: value })); }
  function submit(event: React.FormEvent) { event.preventDefault(); setSubmitted(true); }

  if (submitted) return <main className="checkout-page checkout-success"><div className="success-mark"><Check size={28} /></div><p className="eyebrow">ORDER RECEIVED / FIELD NOTE</p><h1>YOUR<br /><span>RISE.</span></h1><p>Your request is in the edit. We will confirm your delivery details by email and deliver your curated pieces within two weeks.</p><Link className="pink-button" href="/collection">Continue through the edit</Link></main>;
  return <main className="checkout-page"><header className="checkout-header"><Link className="brand" href="/"><span>ZOID</span><i /></Link><span className="secure-label"><LockKeyhole size={13} /> SECURE CHECKOUT</span></header><div className="checkout-wrap"><div className="checkout-intro"><Link className="back-link" href="/collection"><ArrowLeft size={15} /> Back to collection</Link><p className="eyebrow">FIELD / CHECKOUT / {count.toString().padStart(2, "0")} PIECES</p><h1>MAKE THE<br /><span>HANDOFF.</span></h1><p>Every order ships from Lagos and is delivered within two weeks. Your selected sizes are reserved once the order is submitted.</p></div><div className="checkout-grid"><form className="checkout-form" onSubmit={submit}><div className="form-section"><p className="eyebrow">01 / YOUR DETAILS</p><label>Full name<input required value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Your name" /></label><label>Email address<input required type="email" value={form.email} onChange={(event) => update("email", event.target.value)} placeholder="you@example.com" /></label><label>Phone number<input required value={form.phone} onChange={(event) => update("phone", event.target.value)} placeholder="+234" /></label></div><div className="form-section"><p className="eyebrow">02 / DELIVERY</p><label>Delivery address<textarea required value={form.address} onChange={(event) => update("address", event.target.value)} placeholder="Street, city, country" rows={4} /></label></div><button className="pink-button checkout-submit" type="submit">Confirm order <Check size={16} /></button></form><aside className="checkout-summary"><div className="summary-head"><p className="eyebrow">YOUR SELECTION</p><strong>{count.toString().padStart(2, "0")} PIECES</strong></div>{bag.length ? bag.map((item) => <div className="summary-item" key={`${item.slug}-${item.size}`}><img src={item.image} alt="" /><div><strong>{item.name}</strong><small>{item.size} · Qty {item.quantity}</small><span>{item.price}</span></div><button type="button" onClick={() => removeFromBag(item.slug, item.size)} aria-label={`Remove ${item.name}`}><Trash2 size={14} /></button></div>) : <div className="checkout-empty"><p>Your bag is empty.</p><button type="button" onClick={() => navigate("/collection")} className="line-link">Browse the edit <ArrowLeft size={14} /></button></div>}<div className="summary-total"><span>Subtotal</span><strong>{formatNaira(total)}</strong></div><p className="summary-delivery">Delivery / 2 weeks<br />Shipping confirmation follows your order.</p></aside></div></div></main>;
}
