/* ZOID Concrete Ritual: collection browsing is a field index—filterable, tactile, and editorial rather than generic retail. */
import { useMemo, useRef, useState } from "react";
import { useZoidMotion } from "@/hooks/useZoidMotion";
import { useCollectionMotion } from "@/hooks/useCollectionMotion";
import { ArrowDownRight, ArrowLeft, ChevronDown, Filter, Heart, Menu, Search, ShoppingBag, X } from "lucide-react";
import { Link } from "wouter";
import { products } from "@/lib/catalog";
import { useShop } from "@/contexts/ShopContext";

const options = { style: ["All", "Jersey", "Archive", "Heritage", "Gym Kit"], color: ["All", "Black", "Blue", "Red", "White"], size: ["All", "S", "M", "L", "XL"] };
export default function Collection() {
  const pageRef = useRef<HTMLElement | null>(null);
  useZoidMotion(pageRef);
  const [style, setStyle] = useState("All"); const [color, setColor] = useState("All"); const [size, setSize] = useState("All"); const [saved, setSaved] = useState<string[]>([]); const [mobileMenu, setMobileMenu] = useState(false); const { count } = useShop();
  const filtered = useMemo(() => products.filter((product) => (style === "All" || product.style === style) && (color === "All" || product.color === color) && (size === "All" || product.sizes.includes(size))), [style, color, size]);
  const activeCount = [style, color, size].filter((item) => item !== "All").length;
  useCollectionMotion(pageRef, `${style}-${color}-${size}`);
  function clearFilters() { setStyle("All"); setColor("All"); setSize("All"); }
  return <main className="zoid-shell collection-page" ref={pageRef}><header className="topbar"><Link className="brand" href="/"><img src="/zoid-logo.svg" alt="ZOID" /><span>ZOID</span><i /></Link><div className="nav-frame"><span className="nav-context">FIELD / 02</span><nav className={mobileMenu ? "nav-links nav-open" : "nav-links"}><Link href="/">Home</Link><Link className="active" href="/collection">Shop</Link><Link href="/about">About</Link><Link href="/archives">Archives</Link></nav></div><div className="top-actions action-rail"><a className="icon-button" href="/?search=1" aria-label="Search products"><Search size={16} /><small>Search</small></a><Link className="bag-button" href="/"><ShoppingBag size={15} /> {count} Bag</Link><button className="mobile-toggle" aria-label="Toggle menu" onClick={() => setMobileMenu(!mobileMenu)}>{mobileMenu ? <X size={20} /> : <Menu size={20} />}</button></div></header>
    <div className="collection-intro"><div><Link className="back-link" href="/"><ArrowLeft size={15} /> Back to home</Link><p className="eyebrow">THE CURRENT SELECTION / 11 PIECES</p><h1>THE<br /><span>EDIT.</span></h1></div><p className="collection-note"><strong>Curating before creating.</strong> Every piece is selected for the story it carries, the material it holds, and the distance it can travel with you.</p></div>
    <section className="archive-section"><div className="archive-intro"><p className="eyebrow">ZOID / FIELD RECORD 1986—2026</p><h2>THE<br /><span>ROAD.</span></h2><p>Six cuts from the archive. Scroll through the jerseys, places, and persistence that shaped the edit.</p></div><div className="archive-track">{products.slice(0, 6).map((item, index) => <article className="archive-card" key={item.slug}><div className="archive-card-image"><img src={item.image} alt={item.name} /></div><div className="archive-card-meta"><span>0{index + 1} / {item.style.toUpperCase()}</span><h3>{item.name}</h3><p>{item.fit} · {item.color}</p></div></article>)}</div></section>
    <section className="filter-bar"><div className="filter-label"><Filter size={15} /> FILTER / {activeCount.toString().padStart(2, "0")}</div><FilterGroup label="Style" value={style} values={options.style} onChange={setStyle} /><FilterGroup label="Color" value={color} values={options.color} onChange={setColor} /><FilterGroup label="Size" value={size} values={options.size} onChange={setSize} />{activeCount > 0 && <button className="clear-filter" onClick={clearFilters}>Clear all <X size={13} /></button>}</section>
    <section className="collection-grid">{filtered.length ? filtered.map((product, index) => <article className="collection-card" key={product.slug}><Link href={`/product/${product.slug}`} className="collection-image"><img src={product.image} alt={product.name} /><span>0{index + 1}</span><i>FIELD / EVIDENCE</i></Link><div className="collection-card-meta"><div><p className="eyebrow">{product.category}</p><Link href={`/product/${product.slug}`}><h2>{product.name}</h2></Link><small>{product.tone}</small></div><button className="save-card" onClick={() => setSaved((items) => items.includes(product.slug) ? items.filter((item) => item !== product.slug) : [...items, product.slug])} aria-label="Save product"><Heart size={17} fill={saved.includes(product.slug) ? "currentColor" : "none"} /></button></div><div className="collection-card-bottom"><strong>{product.price}</strong><Link className="line-link" href={`/product/${product.slug}`}>View dossier <ArrowDownRight size={14} /></Link></div></article>) : <div className="empty-results"><p className="eyebrow">NO MATCH / ADJUST THE EDIT</p><h2>NOTHING<br /><span>YET.</span></h2><button className="pink-button" onClick={clearFilters}>Reset filters <ArrowDownRight size={16} /></button></div>}</section>
    <footer className="footer"><div className="footer-brand"><Link className="brand" href="/"><img src="/manus-storage/zoid-mark_c4232248.png" alt="" /><span>ZOID</span><i /></Link><p>Curating before creating.<br />Made for the ones still rising.</p></div><div className="footer-bottom"><span>© ZOID STUDIOS / LAGOS — 2026</span><span>Built on grit <b>•</b> Worn with intent</span></div></footer>
  </main>;
}
function FilterGroup({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { const [open, setOpen] = useState(false); return <div className={open ? "filter-group filter-open" : "filter-group"}><button className="filter-trigger" type="button" aria-expanded={open} onClick={() => setOpen((state) => !state)}><span>{label}<small>{value}</small></span><ChevronDown size={14} /></button>{open && <div className="filter-menu" role="listbox" aria-label={`${label} filter`}>{values.map((option) => <button type="button" role="option" aria-selected={value === option} className={value === option ? "filter-option selected" : "filter-option"} key={option} onClick={() => { onChange(option); setOpen(false); }}>{option}{value === option && <span>×</span>}</button>)}</div>}</div>; }
