"""payment refunds and webhook events

Revision ID: c0083f4f1c23
Revises: 3dc56b4fa8db
Create Date: 2026-09-23 15:53:06.799817

"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0083f4f1c23'
down_revision: str | None = '3dc56b4fa8db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default=sa.text("'NGN'"), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'succeeded'"), nullable=False),
    sa.Column('provider_refund_reference', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_provider_refund_reference'), 'refunds', ['provider_refund_reference'], unique=True)
    op.create_index(op.f('ix_refunds_reference'), 'refunds', ['reference'], unique=True)
    op.create_index(op.f('ix_refunds_status'), 'refunds', ['status'], unique=False)
    op.create_index(op.f('ix_refunds_transaction_id'), 'refunds', ['transaction_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_webhook_event_provider_event')
    )
    op.create_index(op.f('ix_webhook_events_kind'), 'webhook_events', ['kind'], unique=False)
    op.create_index(op.f('ix_webhook_events_reference'), 'webhook_events', ['reference'], unique=False)
    op.create_index(op.f('ix_webhook_events_transaction_id'), 'webhook_events', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_transaction_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_reference'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_kind'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_refunds_transaction_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_status'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_reference'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_provider_refund_reference'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
